name: carbon
description: Wanna save the earth?

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  beamer: ^1.0.0
  dartx: ^0.8.0
  diffutil_dart: ^3.0.0
  dotted_border: ^2.0.0
  file_picker: ^4.0.1
  file_saver: ^0.0.6
  flutter_markdown: ^0.6.2
  flutter_svg: ^1.0.0
  flutter_typeahead: ^3.1.3
  gap: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  provider: ^6.0.0
  search_choices: ^2.0.3
  url_launcher: ^6.0.4

dev_dependencies:
  build_runner: ^2.0.4
  flutter_gen_runner: ^4.0.0
  hive_generator: ^1.1.0
  lint: ^1.7.2
  intl_utils: ^2.4.0
  flutter_native_splash: ^1.3.2

#dependency_overrides:
#  build: ^2.0.0 # for hive_generator to be OK

flutter_native_splash:
  color: "#FFFFFF"
  image: "splash_beta.png"

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - colors/colors.xml

flutter_intl:
  enabled: true
  class_name: Translation
  main_locale: fr
  arb_dir: lib/translations
  output_dir: lib/translations/gen

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: VarelaRound
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
